[package]
name = "joebot"
version = "0.1.0"
authors = ["band-of-four"]
edition = "2018"

[build-dependencies]
html5ever = "0.22"
tendril = "0.4"

[dependencies]
rand = "0.6"
reqwest = "0.9"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
redis = "0.9.0"

[profile.release]
opt-level = 2
lto = true
